apiVersion: apps/v1
kind: Deployment
metadata:
  name: textutils-deployment
  labels:
    app: textutils
spec:
  replicas: 4
  selector:
    matchLabels:
      app: textutils
  template:
    metadata:
      labels:
        app: textutils
    spec:
      restartPolicy: Always            # Always, OnFailure, Never
      containers:
      - name: textutils
        image: omsantoshharsule/textutils
        imagePullPolicy: IfNotPresent  # Always, IfNotPresent, Never
        ports:
        - containerPort: 3000