apiVersion: v1
kind: Pod
metadata:
  name: textutils-pod
  labels:
    app: textutils
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: textutils
    image: omsantoshharsule/textutils:latest
    imagePullPolicy: Always  # Always, IfNotPresent, Never
    ports:
    - containerPort: 3000