apiVersion: v1
kind: Service
metadata:
  name: textutils-service
spec:
  selector:
    app: textutils
  type: NodePort                 # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity ClientIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000 
    nodePort: 30004
