apiVersion: apps/v1
kind: Deployment
metadata:
  name: textutils-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textutils-app
  template:
    metadata:
      labels:
        app: textutils-app
    spec:
      restartPolicy: Always            # Always, OnFailure, Never
      containers:
      - name: textutils-app
        image: omsantoshharsule/textutils:v1
        imagePullPolicy: Always  # Always, IfNotPresent, Never
        ports:
        - containerPort: 3000