apiVersion: v1
kind: Service
metadata:
  name: textutils-app-service
spec:
  selector:
    app: textutils-app
  type: LoadBalancer                    # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000